### ISSUE TITLE
APP refinements/bugs

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#6]
after login freeze 
instructions about how to signup (allow popups)

first video needs to be redone: we have to 
also gmail video: make it super short

github video: people don’t really watch it and they jsut go and create github, but then also repository, because this is what github wants from them

in the first lessons of code combat: too slow and too many levels in one so they have hard time skipping
add somewhere also to download gitter app

#### @TODO:
- [ ] add googleplus link
- [ ] Page loading (cache page)
- [ ] Link to "manifest" & "wallofinspiration"
- [ ] "want session in your bezirk" - write us & we try to make it happen
- [ ] add "impressum" + pictures of us + sponsored by wall (fairdust & zweidesign)
- [ ] add #id to each headline to be able to bookmark it

**Comment by ghost** [comment]
- Add IMPRESSUM
- Add Pictures of us
- Add "Voucher Program" Info to page

> Next to it, we were thinking about some kind of "Voucher Program", were we would offer each kid and/or their parents, to find some more kids who would be interested to learn programming.
> That would be great, because it also makes it easier for us to organize collaborative projects, where kids work together on some kind of game or application.

It would work as follows:
Each new kid (brought in through someone who already joined the school) will get 50% OFF for one month, but so will the kid through which the new one came in, thus:
e.g. Ethan brings in four friends (If Ethan brings in more friends, it accumulates)
=> Ethan (50% OFF for four month) OR (100% OFF for the next two months)
In addition: Each kid get 10% OFF permanently for as long as those friends continue to stay with us
Summary:
We might be able to lower the prices in general as soon as we have more kids and some sponsors (please help with any of those)
We can and do offer you a 20% OFF "Early Bird" Discount NOW.
We created our "Voucher Program" to give every participant the option to help us and be rewarded for it
If your company or any "Magic Someone" you might know is willing to sponsor our kids, that would help a lot :-)

**Comment by serapath** [comment]
http://codedoor.org/students.html

**Comment by serapath** [comment]
* codecombat in iframe
* wizardamigos menubar
* chat always visible (during video, during codecombat)
