### ISSUE TITLE
Free Get2Know Workshop (gelbe villa for teenagers)

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#9]
#### @TODO:
- [ ] find places like gelbe villa (for kids)
- [ ] brainstorm email/call  to contact them
- [ ] set up program for workshop

3 options for workshops in the kiez:
- gelbe villa and similar
- coworking
- melis
